version: "3"

services:
  sunflower_broker:
    build:
      image: eclipse-mosquitto
      context: ./sunflower_broker_and_control
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./docker_volume/data:/mosquitto/data
    - ./docker_volume/log:/mosquitto/log
    - ./docker_volume/config:/mosquitto/config/

  sunflower_server:
    build:
      context: ./sunflower_server
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - "8000"
    volumes:
      - ./sunflower_server/staticfiles:/sunflower_server/staticfiles
    depends_on:
      - sunflower_broker
    command: gunicorn sunflower_server.wsgi -b 0.0.0.0:8000

  sunflower_nginx:
    build:
      context: .
      dockerfile: ./sunflower_nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./sunflower_nginx/staticfiles:/usr/share/nginx/html/staticfiles
    environment:
      - NODE_ENV=production
      - VUE_APP_HOST_URL=http://0.0.0.0:80
    depends_on:
      - sunflower_server
